version: '3.8'

services:
  web:
    image: egorsobolev321/flask_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8080:80"
    volumes:
      - .:/code
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
