  deploy: 
    runs-on: ubuntu-latest
    needs: build_and_push
    steps: 
      - name: clone code 
        uses: actions/checkout@v2

      - name: render config 
        run: | 
          mkdir -p deploy 
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml

      - name: copy to server 
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} 
          port: 22
          source: "deploy/docker-compose.yaml"
          target: "flask_app_ci"
          strip_components: 1
         
          rm: true                           
          use_insecure_cipher: true          
